services:
  gomatalk:
    build:
      context: .
      dockerfile: Dockerfile
    image: gomatalk:local
    restart: always
    environment:
      TZ: Asia/Tokyo
    tmpfs: /tmp
    volumes:
      - ./wav:/workspace/wav
      - ./config.toml:/workspace/config/config.toml
      - ./data:/workspace/data
      - ./voices:/workspace/voices
